### ISSUE TITLE
TypeError: Can't instantiate abstract class GEOMDataset with abstract methods get, len

### ISSUE THREAD

**Issue by yonatansverdlov** [mouthful/ClofNet#2]
When I ran your code I have TypeError: Can't instantiate abstract class GEOMDataset with abstract methods get, len.
Maybe because of an old version.
Let me know what needs to be fixed.

**Comment by mouthful** [comment]
Hello,

Upon reviewing the software environment, it appears that there are compatibility conflicts likely due to recent updates in Python or other related packages. To address this, I have updated the scripts that set up the environment, and I can confirm that the previously reported issue has been resolved (at least at my local environment).

To rebuild your Python environment with these changes, please follow the instructions in the updated [readme](https://github.com/mouthful/ClofNet/tree/master#build-environment) or use the revised [environment.yml](https://github.com/mouthful/ClofNet/blob/master/clof_environment.yml) file.

If you still encounter some issues after following these steps, do not hesitate to reach out for further assistance. When doing so, please provide additional context, such as the exact command you are executing and the full error log, to help us better diagnose and resolve your problem.

Best
